### ISSUE TITLE
sdl2:render-copy-ex not implemented

### ISSUE THREAD

**Issue by johntpettit** [lispgames/cl-sdl2#49]
I tried to write it and I'm getting some data type issues.  I'm not too good with autowrap and so forth.  I need to rotate a bitmap I'm loading.

Render-copy-ex is the same as render-copy except it takes three more arguments: an angle (double), a point to rotate around, and options to flip the image.  I was hoping someone had some thoughts on this.  Thanks.

**Comment by rpav** [comment]
I'll take a look. Note however it's generally recommended to use GL for most things like this (load into a texture, render rotated).

**Comment by johntpettit** [comment]
```
(defun render-copy (renderer texture &key source-rect dest-rect)
  "Use this function to copy a portion of the texture to the current rendering target."
  (check-rc (sdl2-ffi.functions:sdl-render-copy renderer texture source-rect dest-rect)))
```

Render copy looks like that.  I wrote the following which is wrong for numerous reasons I don't understand.

```
(defun render-copy-ex (renderer texture &key source-rect dest-rect angle center flip)
  (check-rc (sdl2-ffi.functions:sdl-render-copy-ex renderer texture source-rect dest-rect
						angle center flip)))
```

**Comment by rpav** [comment]
This should more or less work. I've pushed this with the addition of `MASK-APPLY`, which lets you specify keywords rather than manually OR'ing constants or similar.  (Note `sdl-renderer-flip` was previously defined elsewhere in the file.)  You can use a list (out of `(:none :horizontal :vertical)`), a single keyword, or a numeric value.  Please test this, though.

Note that for most of the parameters, you'll probably want to use the utility macros `WITH-POINTS` and `WITH-RECTS`.  See their docstrings for details.

**Comment by johntpettit** [comment]
The mask apply seemed to do the trick.  I kept getting a type error with
out it.  Don't forget to export the function in the package file at some
point.  Thanks so much for this software.  It's going to be fun doing
graphics programming in lisp.

**Comment by rpav** [comment]
Argh! Fixed.  HTH.  Also there's currently a [lisp game jam](http://itch.io/jam/january-2016-lisp-game-jam) going on, if you're not aware.
