### ISSUE TITLE
swank is always being loaded using CCL

### ISSUE THREAD

**Issue by Kipples** [lispgames/cl-sdl2#79]
loading sdl2 will load swank when using CCL. :swank is not in *features* before loading.

**Comment by rpav** [comment]
Was it *previously* in `*features*`?  cl-sdl2 "caches" the load status of swank or slynk due to loading errors should other code depend on it.  This is due to ASDF not being able to really track such dependencies (i.e. change the build depending on changes in `*features*`).

To build without, remove the fasls for cl-sdl2 and compile it again, without swank loaded.  Note to re-enable swank support, you will have to do the same thing.

**Comment by Kipples** [comment]
Thanks, this was exactly it. explains why i was getting different results between lisps.
